### ISSUE TITLE
Some audio channels are missing

### ISSUE THREAD

**Issue by robisaacnz** [ducalex/SimplerS30#1]
This device has an odd audio setup, where the SoC presents a stereo (two channel) interface to SDL, but only outputs one of those channels. This affects cores with strong stereo separation, eg puae and gambatte. It's not clear if this is a badly configured SDL setup or a hardware fault.

**Comment by ducalex** [comment]
I noticed the issue in Gambatte but I never had time to come back to this project so I'm quite eager to try your fix, thanks!

**Comment by ducalex** [comment]
I have merged the patch but can you confirm that the `/opt` path is correct in the configuration? I don't recall `/opt` being symlinked or mapped to /mnt/extsd but I can't verify right now. 

I'll re-open this issue just to remind myself to test it later, feel free to close it if it indeed works as is.

**Comment by robisaacnz** [comment]
`/opt` is not mapped to `/mnt/extsd` in the stock ROM and this was a mistake on my part. I took the patch from a different firmware image and forgot to change the path. It should definitely be `/mnt/extsd` and not `/opt`.

**Comment by ducalex** [comment]
Thanks for checking!
